name: Monitor Sites and Generate Report

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install requests pandas jinja2

      - name: Run Monitoring Script
        working-directory: scripts
        run: python main.py

      - name: Commit and Push DB, Report, and Index to main
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull origin main
          git add data/data.db report.html index.html
          git commit -m "Update site data, report, and index page [automated]" || echo "No changes detected"
          git push origin main

      - name: Deploy Report to Pages Branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          cp report.html /tmp/report.html
          cp index.html /tmp/index.html
          git stash --include-untracked || echo "Nothing to stash"
          if git ls-remote --exit-code origin pages; then
            echo "Pages branch exists. Checking out."
            if ! git checkout -B pages origin/pages; then
              echo "Failed to check out origin/pages; creating orphan branch."
              git checkout --orphan pages
            fi
          else
            echo "Pages branch does not exist. Creating orphan branch."
            git checkout --orphan pages
          fi
          git rm -rf . || true
          cp /tmp/index.html index.html
          cp /tmp/report.html report.html
          git add index.html report.html
          git commit -m "Deploy updated index and report to GitHub Pages" || echo "No changes to deploy"
          git push origin pages --force
